services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ramonbarbosdev/syncdb:latest
    container_name: backend-syncdb
    ports:
      - "8080:8080"
    env_file:
      - .env
