version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ramonbarbosdev/syncdb:latest
    container_name: backend-syncdb
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
