services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    # image: ramonbarbosdev/syncdb:latest
    image: syncdb:latest
    container_name: backend-syncdb
    ports:
      - "8080:8080"
    environment:
     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/syncdb
     SPRING_DATASOURCE_USERNAME: postgres
     SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - backend-network
     
networks:
  backend-network:
    external: true

