version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_DB: syncdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

  spring-app:
    image: backend-syncdb:latest
    container_name: backend-syncdb
    restart: always
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker  # Define o perfil "docker"
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
