services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ramonbarbosdev/syncdb:latest
    container_name: backend-syncdb
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://192.168.10.102:5432/syncdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456X@
