services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ramonbarbosdev/syncdb:latest
    container_name: backend-syncdb
    ports:
      - "8080:8080"
    environment:
     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/syncdb
     SPRING_DATASOURCE_USERNAME: postgres
     SPRING_DATASOURCE_PASSWORD: admin
    networks:
      backend-network:
        ipv4_address: 172.20.0.3
     
networks:
  backend-network:
    external: true

